#fix liel etc.
#cresselia insane def
# can probs remove .995 fix
source('pvp_hax.R')

#good teams?
tapu fini
cresselia
giratina

dusklops
??

rank_team(      '')
#GL (old team)
hax(autocomplete(abomasnow =  T))
hax(autocomplete(`marowak (alolan)` =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(altaria =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(dusknoir =  T))
hax(autocomplete(dusk T))
hax(autocomplete(d T))
hax(autocomplete(swampert =  T))
hax(autocomplete(du T))
hax(autocomplete(dewgong =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(carbink =  T))
hax(autocomplete(skeledirge =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(clefable =  T))
hax(autocomplete(diggersby =  T))
hax(autocomplete(whiscash =  T))
hax(autocomplete(granbull =  T))
hax(autocomplete(marowak =  T))
hax(autocomplete(`marowak (alolan)` =  T))
hax(autocomplete(granbull =  T))
hax(autocomplete(typhlosion =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(clodsire= T))
hax(autocomplete(stunfisk =  T))
hax(autocomplete(`stunfisk (galarian)` =  T))
hax(autocomplete(altaria =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(gastrodon =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(dubwool =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(marowak =  T))
hax(autocomplete(abomasnow =  T))
hax(autocomplete(gastrodon =  T))
hax(autocomplete(typhlosion =  T))
hax(autocomplete(whiscash =  T))
hax(autocomplete(altaria =  T))
hax(autocomplete(clefable =  T))
hax(autocomplete(machamp =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(clefable =  T))
hax(autocomplete(swampert =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(`weezing (galarian)` =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(marowak =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(venusaur =  T))
hax(autocomplete(dunsparce =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(ariados =  T))
hax(autocomplete(drifblim =  T))
hax(autocomplete(drapion =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(serperior =  T))
hax(autocomplete(greninja =  T))
hax(autocomplete(`morpeko (full belly)` =  T))
hax(autocomplete(hypno =  T))
hax(autocomplete(perrserker =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(gastrodon =  T))
hax(autocomplete(drapion =  T))
hax(autocomplete(umbreon =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(meganium =  T))
hax(autocomplete(gligar =  T))
hax(autocomplete(carbink =  T))
hax(autocomplete(froslass =  T))
hax(autocomplete(marowak =  T))
hax(autocomplete(steelix =  T))
hax(autocomplete(`rapidash (galarian)` =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(`weezing (galarian) (shadow)` =  T))
hax(autocomplete(venusaur =  T))
hax(autocomplete(jellicent =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(jumpluff =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(`marowak (alolan)` =  T))
hax(autocomplete(skarmory =  T))
hax(autocomplete(poliwrath =  T))
hax(autocomplete(gligar =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(quagsire =  T))
hax(autocomplete(drilbur =  T))
hax(autocomplete(regirock =  T))
hax(autocomplete(regice =  T))
hax(autocomplete(muk =  T))
hax(autocomplete(abomasnow =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(bastiodon =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(jumpluff =  T))
hax(autocomplete(annihilape =  T))
hax(autocomplete(flygon =  T))
hax(autocomplete(blastoise =  T))
hax(autocomplete(clefable =  T))
hax(autocomplete(jumpluff =  T))
hax(autocomplete(lickilicky =  T))
hax(autocomplete(diggersby =  T))
hax(autocomplete(gastrodon =  T))
hax(autocomplete(clefable =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(umbreon =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(togedemaru =  T))
hax(autocomplete(togetic =  T))
hax(autocomplete(greninja =  T))
hax(autocomplete(salazzle =  T))
hax(autocomplete(malamar =  T))
hax(autocomplete(diggersby =  T))
hax(autocomplete(toxapex =  T))
hax(autocomplete(dedenne =  T))
hax(autocomplete(gliscor =  T))
hax(autocomplete(swampert =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(gastrodon =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(flygon =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(registeel =  T))
hax(autocomplete(mightyena =  T))
hax(autocomplete(castform =  T))
hax(autocomplete(beedrill =  T))
hax(autocomplete(noctowl =  T))
hax(autocomplete(bastiodon =  T))
hax(autocomplete(gallade =  T))
hax(autocomplete(starmie =  T))
hax(autocomplete(drapion =  T))
hax(autocomplete(diggersby =  T))
hax(autocomplete(dubwool =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(drapion =  T))
hax(autocomplete(swampert =  T))
hax(autocomplete(whiscash =  T))
hax(autocomplete(charjabug =  T))
hax(autocomplete(charizard =  T))
hax(autocomplete(lunatone =  T))
hax(autocomplete(feraligatr =  T))
#new team (primeape, mandibuzz, clodsire)
hax(autocomplete(greninja =  T))
hax(autocomplete(granbull =  T))
hax(autocomplete(gligar =  T))
hax(autocomplete(drifblim =  T))
hax(autocomplete(`morpeko (full belly)` =  T))
hax(autocomplete(swampert =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(`morpeko (full belly)` =  T))
hax(autocomplete(ferrothorn =  T))
hax(autocomplete(`morpeko (full belly)` =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(serperior =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(whiscash =  T))
hax(autocomplete(carbink =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(espeon =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(umbreon =  T))
hax(autocomplete(gastrodon =  T))
hax(autocomplete(charizard =  T))
hax(autocomplete(typhlosion =  T))
hax(autocomplete(serperior =  T))
hax(autocomplete(skuntank =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(cresselia =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(serperior =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(goodra =  T))
hax(autocomplete(bastiodon =  T))
hax(autocomplete(`corsola (galarian)` =  T))
hax(autocomplete(`morpeko (full belly)` =  T))
hax(autocomplete(drapion =  T))
hax(autocomplete(dunsparce =  T))
hax(autocomplete(swampert =  T))
hax(autocomplete(swalot =  T))
hax(autocomplete(steelix =  T))
hax(autocomplete(quagsire =  T))
hax(autocomplete(ampharos =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(drapion =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(froslass =  T))
hax(autocomplete(dragonite =  T))
hax(autocomplete(stunfisk =  T))
hax(autocomplete(forretress =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(drifblim =  T))
hax(autocomplete(dunsparce =  T))
hax(autocomplete(mantine =  T))
hax(autocomplete(azumarill =  T))
# hax(autocomplete( T))
hax(autocomplete(krokorok =  T))
hax(autocomplete(jellicent =  T))
hax(autocomplete(ferrothorn =  T))
hax(autocomplete(flygon =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(magcargo =  T))
hax(autocomplete(stunfisk =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(wailord =  T))
hax(autocomplete(togekiss =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(lickilicky =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(lickilicky =  T))
hax(autocomplete(florges =  T))
hax(autocomplete(whiscash =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(whiscash =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(drapion =  T))
hax(autocomplete(primeape =  T))
hax(autocomplete(shiftry =  T))
hax(autocomplete(wigglytuff =  T))
hax(autocomplete(empoleon =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(clodsire =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(`morpeko (full belly)` =  T))
hax(autocomplete(chesnaught =  T))
hax(autocomplete(`weezing (galarian)` =  T))
hax(autocomplete(gastrodon =  T))
hax(autocomplete(mandibuzz =  T))
hax(autocomplete(abomasnow =  T))
hax(autocomplete(azumarill =  T))
hax(autocomplete(`cradily (shadow)` =  T))
#color cup (gastro, alo marowak, amoongus)
#nvm; ultra
hax(autocomplete(`giratina (altered)` =  T))
hax(autocomplete(venusaur =  T))
hax(autocomplete(charizard =  T))w(4/5)
hax(autocomplete(walrein =  T))
hax(autocomplete(rayquaza =  T))
hax(autocomplete(melmetal =  T))w
hax(autocomplete(poliwrath =  T))
hax(autocomplete(typhlosion =  T))
hax(autocomplete(sceptile =  T))l
hax(autocomplete(avalugg =  T))
hax(autocomplete(hydreigon =  T))
hax(autocomplete(togekiss =  T))l
hax(autocomplete(`giratina (altered)` =  T))
hax(autocomplete(greninja =  T))
hax(autocomplete(venusaur =  T))w
hax(autocomplete(typhlosion =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(ampharos =  T))w(3/5)
hax(autocomplete(ampharos =  T))
hax(autocomplete(`giratina (altered)` =  T))
hax(autocomplete(empoleon =  T))w
hax(autocomplete(`mewtwo (armored)` =  T))
hax(autocomplete(lickilicky =  T))
hax(autocomplete(dragonite =  T))l
hax(autocomplete(feraligatr =  T))
hax(autocomplete(`giratina (altered)` =  T))
hax(autocomplete(charizard =  T))w
hax(autocomplete(kyurem =  T))
hax(autocomplete(`muk (alolan)` =  T))
hax(autocomplete(clefable =  T))l
hax(autocomplete(dragonite =  T))
hax(autocomplete(typhlosion =  T))
hax(autocomplete(registeel =  T))w(3/5)
hax(autocomplete(annihilape =  T))
hax(autocomplete(ampharos =  T))
hax(autocomplete(jellicent =  T))w
hax(autocomplete(`tapu bulu` =  T))
hax(autocomplete(`giratina (altered)` =  T))
hax(autocomplete(feraligatr =  T))w
hax(autocomplete(pidgeot =  T))
hax(autocomplete(virizion =  T))
hax(autocomplete(cobalion =  T))l
hax(autocomplete(`kommo-o` =  T))
hax(autocomplete(melmetal =  T))
hax(autocomplete(feraligatr =  T))w
hax(autocomplete(typhlosion =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(primarina =  T))l(3/5)
#bullshit switch advantage: 3/3 no actual advantage for us; 2/2 huge advantage for them
hax(autocomplete(poliwrath =  T))
hax(autocomplete(venusaur =  T))
hax(autocomplete(muk =  T))l (should have been win)
hax(autocomplete(decidueye =  T))
hax(autocomplete(eelektross = T))
hax(autocomplete(typhlosion =  T))l
hax(autocomplete(ursaring =  T))
hax(autocomplete(skeledirge =  T))
hax(autocomplete(charizard =  T))w
hax(autocomplete(steelix =  T))
hax(autocomplete(regirock =  T))
hax(autocomplete(cloyster =  T))w
hax(autocomplete(skeledirge =  T))
hax(autocomplete(greninja =  T))
hax(autocomplete(togekiss =  T))w(3/5)
hax(autocomplete(electivire =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(annihilape =  T))w
hax(autocomplete(togekiss =  T))
hax(autocomplete(ampharos =  T))
hax(autocomplete(skeledirge =  T))w
hax(autocomplete(venusaur =  T))
hax(autocomplete(gengar =  T))
hax(autocomplete(ampharos =  T))w
hax(autocomplete(ampharos =  T))
hax(autocomplete(guzzlord =  T))
hax(autocomplete(skeledirge =  T))l
hax(autocomplete(venusaur =  T))
hax(autocomplete(typhlosion =  T))
hax(autocomplete(swampert =  T))w(4/5)
hax(autocomplete(drapion =  T))
hax(autocomplete(`tapu fini` =  T))
hax(autocomplete(`mewtwo (armored)` =  T))l
hax(autocomplete(dragonite =  T))
hax(autocomplete(galvantula =  T))
hax(autocomplete(feraligatr =  T))l
hax(autocomplete(luxray =  T))
hax(autocomplete(granbull =  T))
hax(autocomplete(pidgeot =  T))l
hax(autocomplete(typhlosion =  T))
hax(autocomplete(greninja =  T))
hax(autocomplete(togekiss =  T))l
hax(autocomplete(typhlosion =  T))
hax(autocomplete(sylveon =  T))
hax(autocomplete(primarina =  T))l(0/5)
hax(autocomplete(talonflame =  T))
hax(autocomplete(`weezing (galarian)` =  T))
hax(autocomplete(guzzlord =  T))w
hax(autocomplete(typhlosion =  T))
hax(autocomplete(`giratina (altered)` =  T))
hax(autocomplete(feraligatr =  T))w
hax(autocomplete(omastar =  T)) #why the extra decimal places?
hax(autocomplete(charizard =  T))
hax(autocomplete(arboliva =  T))w
hax(autocomplete(venusaur =  T))
hax(autocomplete(granbull =  T))
hax(autocomplete(typhlosion =  T))w
hax(autocomplete(dragonite =  T))
hax(autocomplete(skeledirge =  T))
hax(autocomplete(`muk (alolan)` =  T))l(4/5)
hax(autocomplete(ampharos =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(talonflame =  T))l
hax(autocomplete(gengar =  T))
hax(autocomplete(chesnaught =  T))
hax(autocomplete(samurott =  T))w
hax(autocomplete(`giratina (altered)` =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(venusaur =  T))l
hax(autocomplete(`sandslash (alolan)` =  T))
hax(autocomplete(virizion =  T))
hax(autocomplete(cresselia =  T))l
hax(autocomplete(gliscor =  T))
hax(autocomplete(avalugg =  T))
hax(autocomplete(meowscarada =  T))w(2/5)
...
hax(autocomplete(florges =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(`giratina (altered)` =  T))l
hax(autocomplete(ampharos =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(annihilape =  T))w(4/5)
hax(autocomplete(feraligatr =  T))
hax(autocomplete(cresselia =  T))l
hax(autocomplete(venusaur =  T))
hax(autocomplete(skeledirge =  T))
hax(autocomplete(typhlosion =  T))w
hax(autocomplete(clefable =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(drapion =  T))l
hax(autocomplete(greninja =  T))
hax(autocomplete(typhlosion =  T))
hax(autocomplete(sylveon =  T))w
hax(autocomplete(skeledirge =  T))
hax(autocomplete(lickilicky =  T))
hax(autocomplete(primarina =  T))l(2/5)
hax(autocomplete(drapion =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(clefable =  T))w
hax(autocomplete(typhlosion =  T))
hax(autocomplete(`muk (alolan)` =  T))
hax(autocomplete(poliwrath =  T))w
hax(autocomplete(obstagoon =  T))
hax(autocomplete(granbull =  T))
hax(autocomplete(tentacruel =  T))l
hax(autocomplete(skeledirge =  T))
hax(autocomplete(empoleon =  T))
hax(autocomplete(decidueye =  T))w
hax(autocomplete(gliscor =  T))
hax(autocomplete(virizion =  T))
hax(autocomplete(feraligatr =  T))l(3/5)
hax(autocomplete(poliwrath =  T))
hax(autocomplete(talonflame =  T))
hax(autocomplete(swampert =  T))w
hax(autocomplete(skeledirge =  T))
hax(autocomplete(lickilicky =  T))
hax(autocomplete(clefable =  T))w
hax(autocomplete(primeape =  T))
hax(autocomplete(tentacruel =  T))
hax(autocomplete(talonflame =  T))w
hax(autocomplete(annihilape =  T))
hax(autocomplete(clefable =  T))
hax(autocomplete(feraligatr =  T))w
hax(autocomplete(clefable =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(skeledirge =  T))w(5/5)
hax(autocomplete(ampharos =  T))
hax(autocomplete(tentacruel =  T))
hax(autocomplete(typhlosion =  T))w
hax(autocomplete(talonflame =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(`giratina (altered)` =  T))w
hax(autocomplete(genesect =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(golem =  T))l
hax(autocomplete(guzzlord =  T))
hax(autocomplete(feraligatr =  T))
hax(autocomplete(annihilape =  T))l
hax(autocomplete(clefable =  T))
hax(autocomplete(heliolisk =  T))
hax(autocomplete(goodra =  T))l
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))
hax(autocomplete( T))

#toughies
guzzlord
miltank
greninja
hax(autocomplete(snorlax = T))
cresselia tank? or giratina just sucko
hax(autocomplete(milotic = T))

#vanquishments:
hax(autocomplete(talonflame = T))
hax(autocomplete(virizion = T))
hax(autocomplete(feraligatr = T))

hax(autocomplete(`stunfisk (galarian)` = T))
hax(autocomplete(togekiss = T))
hax(autocomplete(swampert = T))

#close ones
hax(autocomplete(togekiss = T))
hax(autocomplete(charizard = T))
hax(autocomplete(poliwrath = T))
